// <auto-generated />
using System;
using BookData.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookData.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20241122065315_M1_new")]
    partial class M1_new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BooksBookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorsAuthorId", "BooksBookId");

                    b.HasIndex("BooksBookId");

                    b.ToTable("Book_Author", (string)null);
                });

            modelBuilder.Entity("BookData.Data.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("9fa0df6c-a977-4b06-9fc5-c8f69143132e"),
                            AuthorImage = "path_to_nguyen_du_image.jpg",
                            AuthorName = "Nguyen Du",
                            Birth = new DateTime(1765, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Nguyen Du was a famous Vietnamese poet, the author of 'The Tale of Kieu.'"
                        },
                        new
                        {
                            AuthorId = new Guid("e5478055-6d08-474e-8048-0f1bc0599d2c"),
                            AuthorImage = "path_to_ho_chi_minh_image.jpg",
                            AuthorName = "Ho Chi Minh",
                            Birth = new DateTime(1890, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Ho Chi Minh was a revolutionary leader and the founder of the Democratic Republic of Vietnam."
                        },
                        new
                        {
                            AuthorId = new Guid("cc76633e-58dd-4494-8cf9-edcbec01eb7c"),
                            AuthorImage = "path_to_tomaso_image.jpg",
                            AuthorName = "Tomaso Marinetti",
                            Birth = new DateTime(1876, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Tomaso Marinetti was an Italian poet and the founder of the Futurist movement."
                        },
                        new
                        {
                            AuthorId = new Guid("27333652-16b9-47d1-bda1-389009338193"),
                            AuthorImage = "path_to_einstein_image.jpg",
                            AuthorName = "Albert Einstein",
                            Birth = new DateTime(1879, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Albert Einstein was a theoretical physicist, known for developing the theory of relativity."
                        },
                        new
                        {
                            AuthorId = new Guid("0467aa65-3e86-4e06-975f-4683371964ad"),
                            AuthorImage = "path_to_virginia_woolf_image.jpg",
                            AuthorName = "Virginia Woolf",
                            Birth = new DateTime(1882, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Virginia Woolf was an English writer, known for works like 'Mrs. Dalloway' and 'To the Lighthouse.'"
                        },
                        new
                        {
                            AuthorId = new Guid("004be899-eeae-4d84-931f-30bd5bc9cab2"),
                            AuthorImage = "path_to_tolstoy_image.jpg",
                            AuthorName = "Leo Tolstoy",
                            Birth = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Leo Tolstoy was a Russian author, best known for novels such as 'War and Peace' and 'Anna Karenina.'"
                        },
                        new
                        {
                            AuthorId = new Guid("cc20bae7-3216-416e-abef-99d75d247eda"),
                            AuthorImage = "path_to_mark_twain_image.jpg",
                            AuthorName = "Mark Twain",
                            Birth = new DateTime(1835, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Mark Twain was an American writer and humorist, famous for books like 'The Adventures of Tom Sawyer.'"
                        },
                        new
                        {
                            AuthorId = new Guid("29205272-1f6a-41cf-8936-4d24ec716b16"),
                            AuthorImage = "path_to_jk_rowling_image.jpg",
                            AuthorName = "J.K. Rowling",
                            Birth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "J.K. Rowling is a British author, best known for writing the 'Harry Potter' series."
                        },
                        new
                        {
                            AuthorId = new Guid("24f739f8-a14f-4882-a11c-d7da3508bf3d"),
                            AuthorImage = "path_to_garcia_marquez_image.jpg",
                            AuthorName = "Gabriel García Márquez",
                            Birth = new DateTime(1927, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Gabriel García Márquez was a Colombian author, famous for works like 'One Hundred Years of Solitude.'"
                        },
                        new
                        {
                            AuthorId = new Guid("7f7f26b0-46ac-49a9-9b77-07532f00e6be"),
                            AuthorImage = "path_to_kafka_image.jpg",
                            AuthorName = "Franz Kafka",
                            Birth = new DateTime(1883, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desciption = "Franz Kafka was a German-speaking Bohemian writer, known for works like 'The Trial' and 'The Metamorphosis.'"
                        });
                });

            modelBuilder.Entity("BookData.Data.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookQRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublicationYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookData.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d32e9f36-baa7-4492-b0a2-683978225375"),
                            AgeLimit = 18,
                            GenreName = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("fb3d734b-3665-4ebc-b783-153c3faa2e9f"),
                            AgeLimit = 15,
                            GenreName = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("ce90b159-3d47-49c8-8fcf-d2d21b29d38a"),
                            AgeLimit = 12,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("6af4bcfe-f100-4558-bf0c-04f88ef57236"),
                            AgeLimit = 18,
                            GenreName = "Biography"
                        },
                        new
                        {
                            Id = new Guid("d456e618-7558-400e-a657-698b3e145c9c"),
                            AgeLimit = 16,
                            GenreName = "Romance"
                        },
                        new
                        {
                            Id = new Guid("aee67c1d-1fe0-4d9d-ab92-9379c3a6ea9e"),
                            AgeLimit = 12,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("34980fcc-3674-4b54-9794-9e58bd003ffa"),
                            AgeLimit = 16,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("7be899d0-1685-4de9-98f8-cc0dcd4db5a8"),
                            AgeLimit = 18,
                            GenreName = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("850fc22d-be17-4921-bcec-62ef74b28b60"),
                            AgeLimit = 14,
                            GenreName = "Historical"
                        },
                        new
                        {
                            Id = new Guid("50548792-b94c-4451-a1da-bbcd1a6febcd"),
                            AgeLimit = 6,
                            GenreName = "Children's Books"
                        });
                });

            modelBuilder.Entity("BookData.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookData.Data.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BookId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<Guid>("BooksBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BooksBookId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("Book_Genre", (string)null);
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BookData.Data.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookData.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookData.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("BookData.Data.Entities.Book", "Book")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookData.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookData.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookData.Data.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookData.Data.Entities.Book", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BookData.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
